[package]
name = "typeshift_solver"
version = "0.1.0"
edition = "2021"
default-run = "typeshift_solver"

[[bin]]
name = "typeshift_solver"
path = "src/main.rs"

[[bin]]
name = "create_index"
path = "src/bin/create_index.rs"

[dependencies]
